import re

linha = '>1A6M:A|PDBID|CHAIN|SEQUENCE'
x = re.search ('>', linha)

if(x):
    print("Linha é um cabeçalho")
else:
    print("Linha não é um cabeçalho")

###################

sequencia_1= ("ATTTCCTGCCCTGAAAGCAGCCTCGAGGGCCAACAACACCTGCTGTCCGTGTCCATGCCCGGTTGGCCACCCCGTTTCTGGGGGGTGAGCGGGGCTTGGCAGGGCTGCGCGGAGGGCGCGGGGGTGGGGCCCGGGGCGGACAGCAGAAGCAGGGTACCCTTTGGGGAGCAGGAGGCCAATAAAAAGTTCAGAGTTCATTGGA")
x = re.findall('AA', sequencia_1)
print(x)

sequencia_2= ("ACCTGCCCTGAAAGCAGCCTCGAGGGCCAACAACACCTGCTGTCCGTGTCCATGCCCGGTTGGCCACCCCGGTGAGCGGGGCTTGGCAGGGCTGCGCGGAGGGCGCGGGGGTGGGGCCCGGGGCGGACAGCAGAAGCAGGGTACCCTTTGGGGAGCAGGAGGCCAATAAAAAGTTCAGAGTTCATTGGA")
y = re.findall('GC', sequencia_2)
print(y)

z_1 = re.search('TT', sequencia_1)
z_2 = re.search ('TT', sequencia_2)
print(z_1)
print(z_2)